sudo: required
services:
  - docker

node_js:
  - "11.10.1"

before_install:
  - docker build -t alucard979/merlin -f Dockerfile.dev .

script:
  - docker run alucard979/merlin npm run test -- --coverage

